In [2]:
import random
import os
import numpy as np

In [32]:
class RandomCatusGenerator:
    # find a seed graph G
    # then find a spanning tree T
    # use T on G extend to a cactus by tries t
    # https://link.springer.com/chapter/10.1007/978-3-030-10448-1_12
    def __init__(self):
        pass
    
    @staticmethod
    def findG(n, p):
        G = np.random.binomial(1, p, n*n).reshape(n, n)
        # self loop ok 
        return G
    
    @staticmethod
    def findT(n, G):
        vis = [False]*n
        T = np.zeros((n,n))
        def dfs(u):
            vis[u] = True
            for v in range(n):
                if(G[u][v] != 0 and not vis[v]):
                    T[u][v] = T[v][u] = 1
                    dfs(v)
                    
        for i in range(n):
            if(not vis[i]):
                dfs(i)
                T[i-1][i] = T[i][i-1] = 1
        return T
    
    @staticmethod
    def findK(n, T, G, t):
        def conflict(x, y):
            pass
        try_time = 0
        K = T
        while(try_time < t):
            u = random.randint(1, n)
            v = random.randint(1, n)
            if(u == v or confilict(u, v)):
                try_time += 1
                continue
            else:
                K[u][v] = K[v][u] = 1
        return K
        
    @staticmethod
    # n = #vertex
    # p = prob of connection to find 
    def generate(n, p, t):
        G = RandomCatusGenerator.findG(n,p)
        T = RandomCatusGenerator.findT(n, G)
        K = RandomCatusGenerator.findK(n, T, G, t)
        return K
        

In [33]:
T = RandomCatusGenerator.generate(10, 0.5, 1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]]
